
#Logging
logging:
  level:
    org:
      springframework: info

#Spring config

#Basic authentication
#spring:
#  security:
#    user:
#      name: juan
#      password: admin

#Spring JPA
spring:
  datasource:
    url: jdbc:postgresql://ec2-3-222-150-253.compute-1.amazonaws.com:5432/djf7g90psnadq
    username: mcvdxsxtxhrrkc
    password: a05081cfe5151b4728c79d83525e4f09eb5ff43e7705ebe1fd1dfbb5208eef29
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    generate-ddl: false
  h2:
    console:
      enabled: true

#Authentication config
jwt:
  signing:
    key:
      secret: mySecret
  get:
    token:
      uri: /authenticate
  refresh:
    token:
      uri: /refresh
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800
