
#Logging
logging:
  level:
    org:
      springframework: info

#Spring security basic auth config
#spring:
#  security:
#    user:
#      name: juan
#      password: admin

#Authentication config
jwt:
  signing:
    key:
      secret: mySecret
  get:
    token:
      uri: /authenticate
  refresh:
    token:
      uri: /refresh
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800
