
#Logging
logging:
  level:
    org:
      springframework: info

#Spring config
#spring:
#  security:
#    user:
#      name: juan
#      password: admin
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

#Authentication config
jwt:
  signing:
    key:
      secret: mySecret
  get:
    token:
      uri: /authenticate
  refresh:
    token:
      uri: /refresh
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800
